import type { Metadata } from "next"; 
import React from "react";
import "./globals.css"; 

export const metadata: Metadata = { 
  title: "Create Next App", 
  description: "Generated by create next app", 
}; 

export default function RootLayout({ 
  children, 
}: Readonly<{ 
  children: React.ReactNode; 
}>) { 
  return ( 
    <html lang="en"> 
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Urbanist:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body 
        style={{ fontFamily: "'Urbanist', sans-serif" }}
        className={`antialiased`} 
      > 
        {children} 
      </body> 
    </html> 
  ); 
}